### ISSUE TITLE
আরও কিছু চেঞ্জ লাগবে (ভার্শন ১.২.১ তে)

### ISSUE THREAD

**Issue by almahmudbd** [almahmudbd/old-masnun-amol#1]
১. সকাল সন্ধ্যার ৫ নাম্বার পেইজের লাস্টে **বিকেলের আমল আগে - সকালেরটা পরে** হয়েছে। এটা রিএরেঞ্জ করা।
https://github.com/almahmudbd/masnun-amol/blob/5d0c9e31960d0ad56f3b1da9bb06435fdecb453e/www/me5.html#L120

২. me4 এ **(শুধু এইটা)** কথাটার ব্র্যাকেট উলটাপালটা হচ্ছে। 
https://github.com/almahmudbd/masnun-amol/blob/5d0c9e31960d0ad56f3b1da9bb06435fdecb453e/www/me4.html#L139

৩. কিছু পেইজে নেক্সট বাটনের পর এখনও একটা করে `<br>` আছে, ওগুলায় ৩টা দেয়া লাগবে।

**Comment by Illusionist3886** [comment]
২ নং এর জন্য issue #2  দেখ। 
৩ নং এর জন্য একবারে শেষের 
`<div class="divider"></div> `
এর পরে নিচের কোড দাও 
```
<div class="center-align mt-2 mb-2">
    <a class="btn waves-effect waves-light center-align" href="bs4.html" style="direction: ltr">
       পরবর্তী &#x2192;
    </a>  
</div>
```

**Comment by almahmudbd** [comment]
১ আর ২ ঠিক করলাম।

**Comment by almahmudbd** [comment]
সব ঠিক করেছি আলহামদুলিল্লাহ
